// Copyright (c) 2026 Arsenova
// SPDX-License-Identifier: MIT
#pragma once

// Public umbrella header for applications that prefer a single include.
// Keep optional backends behind their feature macro so the default facade does
// not require optional system dependencies such as liburing.

#include "vexo/base/check.h"
#include "vexo/base/current_thread.h"
#include "vexo/base/error.h"
#include "vexo/base/panic.h"
#include "vexo/base/singleton.h"
#include "vexo/base/try.h"
#include "vexo/coro/awaitable.h"
#include "vexo/coro/frame_allocator.h"
#include "vexo/coro/scheduler.h"
#include "vexo/coro/spawn.h"
#include "vexo/coro/sync_wait.h"
#include "vexo/coro/task.h"
#include "vexo/coro/work.h"
#include "vexo/ds/bloom_filter.h"
#include "vexo/ds/intrusive_hash_table.h"
#include "vexo/ds/intrusive_list.h"
#include "vexo/ds/intrusive_quadheap.h"
#include "vexo/ds/intrusive_queue.h"
#include "vexo/ds/intrusive_rbtree.h"
#include "vexo/ds/intrusive_splaytree.h"
#include "vexo/ds/murmurhash32.h"
#include "vexo/ds/murmurhash64.h"
#include "vexo/gateway/circuit_breaker.h"
#include "vexo/gateway/fallback_config.h"
#include "vexo/gateway/gateway_server.h"
#include "vexo/gateway/health_check_config.h"
#include "vexo/gateway/load_balancer.h"
#include "vexo/gateway/proxy_pass.h"
#include "vexo/gateway/rate_limiter.h"
#include "vexo/gateway/upstream.h"
#include "vexo/gateway/upstream_conn_pool.h"
#include "vexo/gateway/upstream_peer.h"
#include "vexo/gateway/upstream_registry.h"
#include "vexo/http/http_request.h"
#include "vexo/http/http_response.h"
#include "vexo/http/http_types.h"
#include "vexo/http/router.h"
#include "vexo/io/async_listener.h"
#include "vexo/io/async_stream.h"
#include "vexo/io/buffer.h"
#include "vexo/io/io_backend.h"
#include "vexo/io/stream_algorithms.h"
#include "vexo/log/async_logger.h"
#include "vexo/log/log_buffer.h"
#include "vexo/log/logger.h"
#include "vexo/memory/lru_cache_segment.h"
#include "vexo/memory/memory_pool.h"
#include "vexo/memory/object_pool.h"
#include "vexo/memory/pmr_pool_resource.h"
#include "vexo/memory/pool.h"
#include "vexo/memory/segment_lru_cache.h"
#include "vexo/net/channel.h"
#include "vexo/net/epoll_poller.h"
#include "vexo/net/event_loop.h"
#include "vexo/net/event_loop_scheduler.h"
#include "vexo/net/inet_address.h"
#include "vexo/net/net_utils.h"
#include "vexo/net/poller.h"
#include "vexo/net/reactor_connect.h"
#include "vexo/net/reactor_listener.h"
#include "vexo/net/reactor_stream.h"
#include "vexo/net/socket.h"
#include "vexo/net/timer_queue.h"
#include "vexo/time/timer.h"
#include "vexo/time/timer_id.h"
#include "vexo/time/timer_tree.h"
#include "vexo/time/timestamp.h"
#include "vexo/utils/macros.h"
