// Copyright (c) 2026 Arsenova
// SPDX-License-Identifier: MIT
#pragma once

// Public umbrella header for applications that prefer a single include.
// Keep optional backends behind their feature macro so the default facade does
// not require optional system dependencies such as liburing.

#include "coropact/base/check.h"
#include "coropact/base/current_thread.h"
#include "coropact/base/error.h"
#include "coropact/base/panic.h"
#include "coropact/base/singleton.h"
#include "coropact/base/try.h"
#include "coropact/cache/intrusive_lru.h"
#include "coropact/cache/lru_cache.h"
#include "coropact/cache/sharded_lru_cache.h"
#include "coropact/coro/awaitable.h"
#include "coropact/coro/frame_allocator.h"
#include "coropact/coro/scheduler.h"
#include "coropact/coro/spawn.h"
#include "coropact/coro/sync_wait.h"
#include "coropact/coro/task.h"
#include "coropact/coro/work.h"
#include "coropact/ds/intrusive_hash_table.h"
#include "coropact/ds/intrusive_list.h"
#include "coropact/ds/intrusive_quadheap.h"
#include "coropact/ds/intrusive_queue.h"
#include "coropact/ds/intrusive_rbtree.h"
#include "coropact/ds/intrusive_splaytree.h"
#include "coropact/ds/murmurhash32.h"
#include "coropact/ds/murmurhash64.h"
#include "coropact/gateway/circuit_breaker.h"
#include "coropact/gateway/fallback_config.h"
#include "coropact/gateway/gateway_server.h"
#include "coropact/gateway/health_check_config.h"
#include "coropact/gateway/load_balancer.h"
#include "coropact/gateway/proxy_pass.h"
#include "coropact/gateway/rate_limiter.h"
#include "coropact/gateway/upstream.h"
#include "coropact/gateway/upstream_conn_pool.h"
#include "coropact/gateway/upstream_peer.h"
#include "coropact/gateway/upstream_registry.h"
#include "coropact/http/http_request.h"
#include "coropact/http/http_response.h"
#include "coropact/http/http_types.h"
#include "coropact/http/router.h"
#include "coropact/io/async_listener.h"
#include "coropact/io/async_stream.h"
#include "coropact/io/buffer.h"
#include "coropact/io/io_backend.h"
#include "coropact/io/stream_algorithms.h"
#include "coropact/log/async_logger.h"
#include "coropact/log/log_buffer.h"
#include "coropact/log/logger.h"
#include "coropact/memory/memory_pool.h"
#include "coropact/memory/object_pool.h"
#include "coropact/memory/pmr_pool_resource.h"
#include "coropact/memory/pool.h"
#include "coropact/net/channel.h"
#include "coropact/net/epoll_poller.h"
#include "coropact/net/event_loop.h"
#include "coropact/net/event_loop_scheduler.h"
#include "coropact/net/inet_address.h"
#include "coropact/net/net_utils.h"
#include "coropact/net/poller.h"
#include "coropact/net/reactor_connect.h"
#include "coropact/net/reactor_listener.h"
#include "coropact/net/reactor_stream.h"
#include "coropact/net/reactor_worker.h"
#include "coropact/net/reactor_worker_group.h"
#include "coropact/net/socket.h"
#include "coropact/net/timer_queue.h"
#include "coropact/time/timer.h"
#include "coropact/time/timer_id.h"
#include "coropact/time/timer_tree.h"
#include "coropact/time/timestamp.h"
#include "coropact/utils/macros.h"
